apply plugin: 'com.android.application'

android {
  namespace 'com.uasic.vocabulary'
  compileSdk 35

  defaultConfig {
    applicationId 'com.uasic.vocabulary'
    minSdk 23
    targetSdk 35
    versionCode 3
    versionName '2.0.1'
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}
